DATALOADER:
  DATASET: ImageDatasetPaired
  DATA_PATH: /train.cache/xt.image.enhance.540
  NUM_WORKERS: 20
  XT_TEST_MAX_NUMS: 100
  XT_TEST_TXT: under_dd_over_v3.test.txt
  XT_TRAIN_INPUT_TXT: under_dd_over_v3.train_input.txt
  XT_TRAIN_LABEL_TXT: under_dd_over_v3.train_label.txt
INPUT:
  COLOR_JITTER:
    ADAPTIVE_LIGHT:
      ENABLED: false
      MAX: 1.4
      MIN: 0.6
      STEP: 0.1
    BRIGHTNESS:
      ENABLE: true
      MAX: 1.15
      MIN: 0.8
      STEP: 0.05
    COLOR_TEMPERATURE:
      ENABLED: false
      MAX: 20000
      MID: 6000
      MID_STEP: 1000
      MIN: 2000
      STEP: 500
    CONTRAST:
      ENABLE: false
      MAX: 1.4
      MIN: 0.6
      STEP: 0.1
    HIGH_LIGHT:
      ENABLED: false
      MAX: 40
      MIN: -40
      STEP: 5
    HUE:
      ENABLE: false
      MAX: 0.5
      MIN: -0.5
      STEP: 0.05
    PROB: 0.
    COMPOSE_PROB: 0.
    SATURATION:
      ENABLE: false
      MAX: 1.4
      MIN: 0.6
      STEP: 0.1
  DOWN_FACTOR: 1
  FLIP:
    RATION: 0.05
  INPUT_OVER_EXPOSURE:
    ENABLED: false
    F_MAX: 0.01
    F_MIN: -1.5
    F_VALUE: 0.85
  TRAINING_COLOR_JITTER:
    ENABLE: false
MODEL:
  ARCH: DceModel
  NETWORK:
    ARCH: DceNet
    DCE_NET:
      KERNEL_NUMBER: 16
  DEVICE: cuda
  VGG:
    LAYER: 22
    PATH: /mnt/sdb/pretrain.model/vgg.model/pytorch/vgg16-397923af.pth
  WEIGHTS: ''
  WEIGHTS_INIT_TYPE: none
OUTPUT_DIR: /mnt/sda1/train.output/enhance.output/img.dce
OUTPUT_LOG_NAME: dce
SOLVER:
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    ENABLED: true
    GROUP: true
  LOSS:
    LAMBDA_COL: 5
    LAMBDA_EXP: 10
    LAMBDA_PIXEL: 100
    LAMBDA_SPA: 1.0
    LAMBDA_TV: 1600
    LAMBDA_VGG: 0.5
  LR_SCHEDULER:
    ENABLED: true
    GAMMA: 0.5
    STEPS: (100000, 180000)
  MAX_ITER: 220000
  MAX_KEEP: 100
  OPTIMIZER:
    BASE_LR: 0.0001
    WEIGHT_DECAY: 0.
    ADAM:
      B1: 0.9
      B2: 0.999
  TEST_PER_BATCH: 4
  TRAIN_PER_BATCH: 2